apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-alb-ingress
  namespace: ticketing
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:857281493476:certificate/0eb146df-534e-4aa0-95e1-e348499a54ba
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - host: 
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /next
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /db-test
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /seats
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ticket-frontend-svc
            port:
              number: 80
  - host: www.pluseticket.store
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /next
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /db-test
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /seats
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-svc
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ticket-frontend-svc
            port:
              number: 80
